# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('name_es', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('slug', models.SlugField()),
                ('order', models.PositiveIntegerField(default=0, verbose_name=b'Orden')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tags.Tag', verbose_name='Categor\xeda padre')),
            ],
            options={
                'verbose_name': 'Categor\xeda',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('parent', 'slug')]),
        ),
    ]
